export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';
export const SET_LOGIN_FAILURE = 'SET_LOGIN_FAILURE';
